Denuncias/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from denuncia.views import busquedaMo, denunciar, success
from usuario.views import cerrar, inicio, confirmarPass
from localizaciones.views import mapa

urlpatterns = [
    url(r'^a84cdb3a7c1d949ede1fc3a72a1e781d3f4de971/', admin.site.urls),
    url(r'^logout/', cerrar, name='logout'),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^institucion/', include('institucion.urls', namespace='institucion')),
    url(r'^$', inicio,name='inicio'),
    url(r'^denunciar/',denunciar,name='denunciar'),
    url(r'^denuncias/', include('denuncia.urls', namespace='denuncias')),
    url(r'^success/', success, name = 'success'),
    url(r'^busqMot/', busquedaMo, name='mots'),
    url(r'^estadisticas/', include('localizaciones.urls', namespace="local")),
    url(r'^mapa/', mapa,name="mapa"),
    url(r'^confirmar/', confirmarPass, name='confirmarPass'),
    # url(r'^push/', include('gcm.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#else:
#    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#            {'document_root': settings.STATIC_ROOT}),

localizaciones/urls.py
from django.conf.urls import url, include

from tastypie.api import Api

from .views import (
        busquedaM,
        busquedaD,
        obtenerD,
        estadisticas,
        municipioDetail,
        detalleZona,
        respuesta_municipio
        )
from .api import (
        DepartamentoResource,
        MunicipioResource,
        DireccionResource
        )

local_api = Api(api_name='local')
local_api.register(DepartamentoResource())
local_api.register(MunicipioResource())
local_api.register(DireccionResource())

urlpatterns = [

    url(r'^busqM/',busquedaM, name='muni'),
    url(r'^busqD/', busquedaD, name = 'dirs'),
    url(r'^obtD/', obtenerD, name='dens'),
    url(r'^muni_response/', respuesta_municipio, name='respuesta_municipio'),
    url(r'^$',estadisticas, name="estadisticas"),
    url(r'^detalleZona/', detalleZona, name='detalleZona'),
    url(r'^(?P<dep>\w+)/(?P<muni>\w+)$',municipioDetail,name='mDetail'),
    url(r'^api/', include(local_api.urls)),
]

usuario/urls.py
from django.conf.urls import url

from .views import (
                    privado,
                    registro,
                    usuarioList,
                    UsuarioDetail,
                    UsuarioEdit,
                    cambiarPass,
                    cambiarCorreo
                    )
from denuncia.views import denunciasList, DenunciaDetail

urlpatterns = [
    url(r'^$', privado, name='privado'),
    url(r'^denuncias/$', denunciasList, name='lista'),
    url(r'^denuncias/(?P<pk>\d+)/detalles/', DenunciaDetail.as_view(), name='detalles'),
    url(r'^usuarios/crear/$', registro, name="registro"),
    url(r'^usuarios/$', usuarioList, name="lista_u"),
    url(r'^usuarios/(?P<slug>\w+)/detalles/$', UsuarioDetail.as_view(), name="detalles_u"),
    url(r'^usuarios/(?P<slug>\w+)/editar/$', UsuarioEdit.as_view(), name="editar_u"),
    url(r'^cambiar_contrasena/', cambiarPass, name='cambiarPass'),
    url(r'^cambiar_correo/', cambiarCorreo, name='cambiarCorreo')

]

usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser


"""
Gestor de usuarios personalizado. Crea usuarios bajo las necesidades de la app.
Hereda del gestor base de Django. (BaseUserManager)

--------------------------------------------------------------------------------
|     VARIABLE     |       TIPO      |              DESCRIPCION                |
-------------------+-----------------+------------------------------------------
|    create_user   |      funcion    |  Retorna un objeto Usuario, un usuario  |
|                  |                 |  normal con privilegios limitados.      |
--------------------------------------------------------------------------------
| create_superuser |      funcion    |  También retorna un objero Usuario, pero|
|                  |                 |  con privilegios de superusuario,       |
|                  |                 |  utilizando el metodo 'create_user'.    |
--------------------------------------------------------------------------------
"""
class UsuarioManager(BaseUserManager):

    def create_user(self, username, correo, nombre, apellidos, password=None):

        #Si falta alguno de esos valores, o no es valido,
        #lanza un error de Valor.
        if not username:
            raise ValueError('Ingrese un nombre de usuario valido.')
        if not correo:
            raise ValueError('Ingrese una direccion de correo valida.')
        if not nombre:
            raise ValueError('Ingrese uno o mas nombres.')
        if not apellidos:
            raise ValueError('Ingrese sus apellidos.')

        #Se crea al usuario utilizando su modelo.
        usuario = self.model(
            username = username,
            correo = self.normalize_email(correo),
            nombre = nombre,
            apellidos = apellidos
        )

        #Se setea la contraseña, el metodo 'set_password' aplica el hash al
        #texto plano de la contraseña y lo guarda en el campo 'password' del
        #modelo usuario.
        usuario.set_password(password)
        #Se guarda el usuario en la tabla.
        usuario.save()

        return usuario

    def create_superuser(self, username, correo, nombre, apellidos, password=None):

        #Se crea al usuario normal.
        usuario = self.create_user(username, correo, nombre, apellidos, password)
        #Se le asignan los privilegios.
        usuario.is_admin = True
        usuario.is_staff = True
        usuario.is_active = True
        #Se guarda.
        usuario.save()

        return usuario


"""
Modelo que guarda a los usuarios, tiene como gestor a UsuarioManager, hereda de
AbstractBaseUser.

--------------------------------------------------------------------------------
|     VARIABLE     |       TIPO      |              DESCRIPCION                |
-------------------+-----------------+------------------------------------------
|        id        |       PK        |  Llave primaria de Usuario.             |
|                  |      (INT)      |                                         |
--------------------------------------------------------------------------------
|      nombre      |  CharField(55)  |  Nombre o nombres del usuario. Es       |
|                  |                 |  obligatorio.                           |
--------------------------------------------------------------------------------
|     apellidos    |  CharField(55)  |  Apellidos del usuario. Es obligatorio. |
--------------------------------------------------------------------------------
|     username     |  CharField(25)  |  Nombre de usuario. Es obligatorio.     |
--------------------------------------------------------------------------------
|      correo      |   EmailField    |  Correo del usuario. Es obligatorio y   |
|                  |                 |  unico.                                 |
--------------------------------------------------------------------------------
|  ultima_conexion |  DateTimeField  |  Informa cuando fue la ultima vez que el|
|                  |                 |  usuario se conecto al sistema.         |
--------------------------------------------------------------------------------
|     is_staff     |  BooleanField   |  Identifica al usuario como             |
|                  |                 |  superusuario.                          |
--------------------------------------------------------------------------------
|     is_admin     |  BooleanField   |  Identifica al usuario como usuario con |
|                  |                 |  con privilegios medios.                |
--------------------------------------------------------------------------------
|      is_res      |  BooleanField   |  Identifica al usuario como usuario de  |
|                  |                 |  privilegios bajos. Usuario promedio.   |
--------------------------------------------------------------------------------
|    is_active     |  BooleanField   |  Define si el usuario está activo.      |
--------------------------------------------------------------------------------
|    institucion   |       FK        |  Relacion con el modelo Institucion,    |
|                  |                 |  indica a que institucion pertenece el  |
|                  |                 |  usuario.                               |
--------------------------------------------------------------------------------
|       zona       |       FK        |  Relacion con el modelo Direccion,      |
|                  |                 |  indica la ubicacion del usuario.       |
--------------------------------------------------------------------------------
|      objects     |  UsuarioManager |  Indica que gestor de objetos utiliza   |
|                  |                 |  el modelo.                             |
--------------------------------------------------------------------------------
|  USERNAME_FIELD  |      String     |  Indica que campo de la clase se        |
|                  |                 |  utiliza como nombre de usuario.        |
--------------------------------------------------------------------------------
|  REQUIRED_FIELDS |      lista      |  Indica que campos son obligatorios.    |
--------------------------------------------------------------------------------
|   get_full_name  |     funcion     |  Retorna la concatenacion de 'nombre' y |
|                  |                 |  'apellidos' del usuario.               |
--------------------------------------------------------------------------------
|  get_short_name  |     funcion     |  Retorna el 'nombre' del usuario.       |
--------------------------------------------------------------------------------
|    __unicode__   |     funcion     |  Representación del obejto como una     |
|                  |                 |  cadena, en este caso, es el 'username'.|
--------------------------------------------------------------------------------
| has_module_perms |     funcion     |  Funcion que compara permisos del       |
|                  |                 |  usuario, en este modelo no se utiliza, |
|                  |                 |  siempre retorna verdadero.             |
--------------------------------------------------------------------------------
|    has_perm      |     funcion     |  Funcion que compara el permiso del     |
|                  |                 |  usuario, en este modelo no se utiliza, |
|                  |                 |  siempre retorna verdadero.             |
--------------------------------------------------------------------------------
"""
class Usuario(AbstractBaseUser):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=55)
    apellidos = models.CharField(max_length=55)
    username = models.CharField(max_length=25, unique=True)
    correo = models.EmailField(unique=True)
    ultima_conexion = models.DateTimeField(auto_now_add=True, auto_now=False)
    #Permisos a todo el sistema.
    is_staff = models.BooleanField(default=False)
    #Permisos al sistema de denuncias por departamento e institucion.
    #Se otorga a usuarios de analisis.
    is_admin = models.BooleanField(default=False)
    #Permisos al sistema de denuncias por departamento e institucion.
    #Solo de los ultimos 7 dias.
    #Se otorga a usuarios de respuesta.
    is_res = models.BooleanField(default=True)

    is_active = models.BooleanField(default=False)

    institucion = models.ForeignKey('institucion.Institucion', default = 1)
    zona = models.ForeignKey('localizaciones.Direccion', default = 1)

    objects = UsuarioManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['nombre', 'apellidos', 'correo']

    def get_full_name(self):
        return self.nombre + " " + self.apellidos

    def get_short_name(self):
        return self.nombre

    def __unicode__(self):
        return self.username

    def has_module_perms(self, perm_list):
        return True

    def has_perm(self, perm):
        return True

usuario/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.core.mail import EmailMultiAlternatives

from .models import Usuario

class InicioForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

class CambioPassForm(forms.Form):

    actual = forms.CharField(label='Password', widget=forms.PasswordInput())
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())

    def clean_password1(self):

        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password and password1 and password != password1:
            raise forms.ValidationError("Las contraseñas no coinciden.")
        if password and password1 and len(password) < 8:
            raise forms.ValidationError("Ingrese una contraseña más larga.")

        return password1


class UserCreationForm(forms.ModelForm):

    # password = forms.CharField(label='Password', widget=forms.PasswordInput())
    # password1 = forms.CharField(label='Password', widget=forms.PasswordInput())

    class Meta:
        model = Usuario
        fields = [
            'nombre',
            'apellidos',
            'username',
            'correo',
            'institucion',
            'zona'
        ]

    # def clean_password1(self):
    #
    #     password = self.cleaned_data.get("password")
    #     password1 = self.cleaned_data.get("password1")
    #
    #     if password and password1 and password != password1:
    #         raise forms.ValidationError("Las contraseñas no coinciden.")
    #     if password and password1 and len(password) < 8:
    #         raise forms.ValidationError("Ingrese una contraseña más larga.")
    #
    #     return password1

    def save(self, commit=True):

        usuario = super(UserCreationForm, self).save(commit=False)
        contrasena = Usuario.objects.make_random_password()

        text_content = 'Denuncia Movil: Contraseña y usuario.'
        html_content = '''<!DOCTYPE html><html><body><h1> Hola
                            ''' + str(self.cleaned_data.get("nombre"))+' '+str(self.cleaned_data.get("apellidos")) + '''</h1></br>
                            <h3> Este mensaje es para entregarte tu contraseña
                            y confirmar tu nombre de usuario.</h3><br>
                            <h4>Nombre de Usuario: ''' + str(self.cleaned_data.get("username")) + '''</h4></br>
                            <h4>Contraseña: ''' + str(contrasena) + '''</h4></br></body>
                            <footer><i>Los archivos quedan a cargo de la
                             entidad indicada.</i><br>
                            <i>Todos los datos de este correo son
                             confidenciales y no deben ser difundidos
                            a nadie más que las entidades interesadas
                             en ellos.</i></footer></html>'''

        from_email = '"Denuncia Movil" <denunciamovil@gmail.com>'
        msg = EmailMultiAlternatives(
            "Usuario y contraseña",
             text_content,
              from_email,
              [self.cleaned_data.get("correo")]
            )
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        usuario.set_password(contrasena)

        if commit:
            usuario.save()

        return usuario

templates/usuario/denuncia_detail.html
{% extends 'base.html' %}

{% block title %}
Denuncia No. {{denuncia.id}}
{% endblock %}

{% block head %}
<h1>Denuncia No. {{denuncia.id}} | <i>{{denuncia.motivo}}, {{denuncia.motivo.institucion}}</i></h1>
{% endblock %}

{% block content %}
<div id='section'>
  <div id="linkbar">
    <span class="inlinkbar">
      <ul>
        <li><a href={% url 'usuario:privado' %}><span>Perfil</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href={% url 'usuario:lista' %}><span>Denuncias</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href=""><span>Denuncia No. {{denuncia.id}}</span></a></li>
      </ul>
    </span>
  </div>
  <table class="table" style="color: black;">
      <tr>
        <th>ID</th>
        <td>{{denuncia.id}}</td>
      </tr>
      <!-- <tr>
        <th>Nombre</th>
        <td>{{denuncia.nombre}}</td>
      </tr>
      <tr>
        <th>DPI</th>
        <td>{{denuncia.dpi}}</td>
      </tr>
      <tr>
        <th>Telefono</th>
        <td>{{denuncia.telefono}}</td>
      </tr> -->
      <tr>
        <th>Fecha</th>
        <td>{{denuncia.fecha}}<h6><!--<a href="#">Más de esta fecha.</a></h6>--></td>
      </tr>
      <tr>
        <th>Motivo</th>
        <td>{{denuncia.motivo}}</td>
      </tr>
      <tr>
        <th>Denuncia</th>
        <td><p><i>{{denuncia.denuncia}}</i></p></td>
      </tr>
      <tr>
        <th>Direccion</th>
        <td>{{denuncia.direccion}},  <i>{{denuncia.direccion.municipio}}, {{denuncia.direccion.municipio.departamento}}</i></td>
      </tr>
      <tr>
        <th>Referencia</th>
        <td>{{denuncia.referencia}}</td>
      </tr>
      {% if geo %}
      <tr>
        <th>Ubicación</th>
        <td><img src="https://maps.googleapis.com/maps/api/staticmap?center={{denuncia.latitud}},{{denuncia.longitud}}&markers=color:0x3067B0%7Clabel:{{label}}%7C{{denuncia.latitud}},{{denuncia.longitud}}&zoom=17&size=400x200&key=AIzaSyAPIn8C1d9dQLNNnv-Z2D0AKz6WESeZ8tI" alt="Ubicación" /></td>
      </tr>
      {% endif %}
  </table>
</div>
{% endblock %}

templates/usuario/privado.html
{% extends 'base.html' %}

{% block title %}
  {{user.get_full_name}}
{% endblock %}

{% block head %}
  <!-- <h1>¡Bienvenido {{user}}!</h1> -->
{% endblock %}

{% block content %}
<div id="section">
  <div class = "tablaCentro" style="position: relative; right: 30%;">
    <table class="table">
      <tr>
          <td>Nombre de usuario</td>
          <td><i>{{user}}</i></td>
      </tr>
      <tr>
          <td>Correo</td>
          <td><i>{{user.correo}}</i></td>
      </tr>
      <tr>
          <td>Institucion</td>
          <td><i>{{user.institucion}}</i></td>
      </tr>
      <tr>
          <td>Ultima conexion</td>
          <td><i>{{user.ultima_conexion}}</i></td>
      </tr>
      <tr>
          <td>Tipo de Usuario</td>
          <td><i>
            {% if user.is_staff %}
            Super Usuario
            {% elif user.is_admin %}
            Analisis
            {% elif user.is_res %}
            Respuesta
            {% endif %}
          </i></td>
      </tr>
    </table>
    <table style="position: relative; top: 18%;">
      <tr>
        {% if user.is_staff %}
        <td><a href={% url 'usuario:lista_u' %}><span> Usuarios </span></a></td>
        <td><span>|</span></td>
        {% endif %}
        <td><a href={% url 'usuario:cambiarPass' %}><span>Cambiar Contraseña</span></a></td>
        <td><span>|</span></td>
        <td><a href={% url 'usuario:cambiarCorreo' %}><span>Configurar Correo</span></a></td>
        <!-- <td><span>|</span></td>
        <td><a href="#"><span>d</span></a></td> -->
      </tr>
    </table>
  </div>
  <div id="line-chart">

  </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
google.charts.load('current', {'packages':['line']});
      google.charts.setOnLoadCallback(drawChart);

    function drawChart() {

      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Día');
      data.addColumn('number', "{{tiempo1}}");
      data.addColumn('number', "{{tiempo2}}");
      data.addColumn('number', "{{tiempo3}}");


      data.addRows([
        {% for dia, cant1, cant2, cant3 in denuncias %}
          ['{{dia}}', {{cant1}}, {{cant2}}, {{cant3}}],
        {% endfor %}
      ]);

      var options = {
        chart: {
          title: 'Denuncias mensuales.',
          subtitle: 'Ultimos 3 meses.'
        },
        // width: 700,
        // height: 400,
        // animation: {
        //   duration: 1500,
        //   easing: 'out',
        //   startup: true,
        // },
      };

      var chart = new google.charts.Line(document.getElementById('line-chart'));

      chart.draw(data, options);
    }

</script>
{% endblock %}

templates/usuario/usuario_detail.html
{% extends 'base.html' %}

{% block title %}
{{usuario.username}}
{% endblock %}

{% block head %}
<h1>{{usuario.get_full_name}}, <i>{{usuario.username}}</i></h1>
{% endblock %}

{% block content %}
<div id="section">
  <div id="linkbar">
    <span class="inlinkbar">
      <ul>
        <li><a href={% url 'usuario:privado' %}><span>Perfil</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href={% url 'usuario:lista_u' %}><span>Usuarios</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href=""><span>{{usuario}}</span></a></li>
      </ul>
    </span>
  </div>
  <table class="table" style="color: black;">
      <tr>
        <th>ID</th>
        <td>{{usuario.id}}</td>
      </tr>
      <tr>
        <th>Nombre</th>
        <td>{{usuario.get_full_name}}</td>
      </tr>
      <!-- <tr>
        <th>DPI</th>
        <td></td>
      </tr> -->
      <tr>
        <th>Usuario</th>
        <td>{{usuario}}</td>
      </tr>
      <tr>
        <th>Correo</th>
        <td>{{usuario.correo}}</td>
      </tr>
      <tr>
        <th>Ultima Conexión</th>
        <td>{{usuario.ultima_conexion}}</td>
      </tr>
      {% if usuario.is_active %}
      <tr>
        <th>Activo</th>
        <td>Si</td>
      </tr>
      {% else %}
      <tr>
        <th>Activo</th>
        <td>No</td>
      </tr>
      {% endif %}
      <tr>
        <th>Institucion</th>
        <td>{{usuario.institucion}}</td>
      </tr>
      <tr>
        <th>Tipo</th>
        <td>
          <p>
            <i>
              {% if usuario.is_staff %}
              Super Usuario
              {% elif usuario.is_admin %}
              Analisis
              {% elif usuario.is_res %}
              Respuesta
              {% endif %}
            </i>
          </p>
        </td>
      </tr>
      <tr>
        <th>Zona</th>
        <td>
          <p>
            <i>
              {{usuario.zona}},
               {{usuario.zona.municipio}},
               {{usuario.zona.municipio.departamento}}
            </i>
          </p>
        </td>
      </tr>
  </table>
</div>
{% endblock %}

templates/usuario/usuario_edit.html
{% extends 'base.html' %}

{% block title %}
Editar {{usuario}}
{% endblock %}

{% block head %}
<h1>{{usuario.get_full_name}}, <i>{{usuario.username}}</i></h1>
{% endblock %}

{% block content %}
<div id ="section">
  <div id="linkbar">
    <span class="inlinkbar">
      <ul>
        <li><a href={% url 'usuario:privado' %}><span>Perfil</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href={% url 'usuario:lista_u' %}><span>Usuarios</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href=""><span>Editar {{usuario}}</span></a></li>
      </ul>
    </span>
  </div>
  <div id="bloqueForms">

    </br>
    </br>
    </br>
    </br>
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <div>
          <label>Nombre</label></br>
          {{form.nombre}}</br>
        </div>
        <div>
          <label>Apellidos</label></br>
          {{form.apellidos}}</br>
        </div>
        <div>
          <label>Correo</label></br>
          {{form.correo}}</br>
        </div>
        <div>
          <label>SU</label></br>
          {{form.is_staff}}</br>
        </div>
        <div>
          <label>Analisis</label></br>
          {{form.is_admin}}</br>
        </div>
        <div>
          <label>Respuesta</label></br>
          {{form.is_res}}</br>
        </div>
        <div>
          <label>Activo</label></br>
          {{form.is_active}}</br>
        </div>
        <div>
          <label>Institucion</label></br>
          {{form.institucion}}</br>
        </div>
        <div>
          <label>Departamento</label></br>
          <select id="deps" class="" name="deps1">
            <option value="0" selected>------</option>
            {% for departamento in departamentos %}
            <option value="{{departamento.id}}" {% if departamento.id == user.zona.municipio.departamento.id %} selected {% endif %}>{{departamento}}</option>
            {% endfor %}
          </select></br>
        </div>
        <div>
          <label>Municipio</label></br>
          <select id="muni" class="" name="muni1">
            <option value="0" selected>------</option>
          </select></br>
        </div>
        <div>
          <label>Zona</label></br>
          {{form.zona}}</br>
        </div>
        <div>
          <label>Institucion</label></br>
          {{form.institucion}}</br>
        </div>
        <div id="btnForm">
          <input type="submit" class="btn btn-default" value="Guardar">
        </div>
      </div>
    </form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">

  $('#deps').on('change', busquedaMuni);
  $(document).ready(busquedaMuni);
  $('#muni').on('change', busquedaDir);
  $('#id_is_staff').on('change', seleccionar);
  $('#id_is_admin').on('change', seleccionar);
  $('#id_is_res').on('change', seleccionar);

  document.getElementById('id_zona').length = 0;

  function busquedaMuni(){

    var id = $('#deps').val();
    $.ajax({

      data: {'id': id},
      url: "{% url 'local:muni' %}",
      type: 'get',
      success: function(data){

        var inner = document.getElementById('muni');

        inner.innerHTML = "";
        var p = document.createElement("option");

        var municipio = "{{user.zona.municipio}}";

        // console.log(data[i].fields.nombre)

        p.value = "0";
        p.innerHTML = "------";

        inner.options.add(p);
        for (var i = 0; i<data.length; i++){

          var nuevo = document.createElement("option");

          // console.log(data[i].fields.nombre)

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.nombre;
          if(nuevo.innerHTML == municipio)
            nuevo.selected = true;

          inner.options.add(nuevo);

        }

        busquedaDir();

      }

    })

  }

  function busquedaDir(){

    var id = $('#muni').val();
    $.ajax({

      data: {'id': id},
      url: "{% url 'local:dirs' %}",
      type: 'get',
      success: function(data){
        document.getElementById('id_zona').length = 0;

        var inner = document.getElementById('id_zona');
        var zona = '{{user.zona}}';

        for(var i = 0; i<data.length; i++){

          var nuevo = document.createElement("option");

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.direccion;

          if(nuevo.innerHTML == zona)
            nuevo.selected = true;

          inner.options.add(nuevo);

        }

      }

    })

  }

  function seleccionar(){
    // $(this).prop('checked')
    var check = $(this);

    var lista = $('input[type=checkbox]');

    for (var i = 0; i < lista.length - 1; i++) {
      if(lista[i]!=check[0]){
        lista[i].checked = false;
      }
    }

  }

</script>
{% endblock %}

templates/usuario/usuarios_list.html
{% extends 'base.html' %}

{% block title %}
Lista de Usuarios
{% endblock %}

{% block head %}
<h1>USUARIOS</h1>
{% endblock %}

{% block content %}
<div id="section">
  <div id="linkbar">
    <span class="inlinkbar">
      <ul>
        <li><a href={% url 'usuario:privado' %}><span>Perfil</span></a></li>
        <li><span style="color: black;"><i>/</i></span></li>
        <li><a href=""><span>Usuarios</span></a></li>
        <!-- <li><span style="color: black;"><i>////</i></span></li>
        <li>
          <select>
            <option selected>------</option>
          </select>
        </li> -->
      </ul>
    </span>
  </div>
  <table id='tblDatos' class="table" style="color: black;">
    <tr>
      <th>ID</th>
      <th>Nombre y Apellidos</th>
      <th>Usuario</th>
      <th>Institucion</th>
      <!-- <th>En linea</th> -->
      <th>Activo</th>
    </tr>
    {% for usuario in usuarios %}
    <tr>
      <td>{{usuario.id}}</td>
      <td>{{usuario.get_full_name}}</td>
      <td>{{usuario.username}}</td>
      <td><a href='?institucion={{usuario.institucion}}'>{{usuario.institucion}}</a></td>
      <!-- <td id='active'>
        <a id='{{usuario.id}}' class='activate' href="#">
          <span>
            {% if usuario.is_active %}
            Activo
            {% else %}
            Inactivo
            {% endif %}
          </span>
        <a>
      </td> -->
      <!-- <td>
        {% if usuario.is_authenticated %}
        Si
        {% else %}
        No
        {% endif %}
      </td> -->
      <td>
        {% if usuario.is_active %}
        Si
        {% else %}
        No
        {% endif %}
      </td>
      <td>
        <a href={% url 'usuario:detalles_u' usuario.username %}>Ver</a>
         |
        <a href={% url 'usuario:editar_u' usuario.username %}>Editar</a>
      </td>
    </tr>
    {% endfor %}
  </table>
  <div id="paginador"></div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
  // $('#deactivate').on('click',function(){
  //   alert('funciona');
  // })
  var p = new Paginador(
    document.getElementById('paginador'),
    document.getElementById('tblDatos'),
    10
  );
  p.Mostrar();
</script>
{% endblock %}