Denuncias/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from denuncia.views import busquedaMo, denunciar, success
from usuario.views import cerrar, inicio, confirmarPass
from localizaciones.views import mapa

urlpatterns = [
    url(r'^a84cdb3a7c1d949ede1fc3a72a1e781d3f4de971/', admin.site.urls),
    url(r'^logout/', cerrar, name='logout'),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^institucion/', include('institucion.urls', namespace='institucion')),
    url(r'^$', inicio,name='inicio'),
    url(r'^denunciar/',denunciar,name='denunciar'),
    url(r'^denuncias/', include('denuncia.urls', namespace='denuncias')),
    url(r'^success/', success, name = 'success'),
    url(r'^busqMot/', busquedaMo, name='mots'),
    url(r'^estadisticas/', include('localizaciones.urls', namespace="local")),
    url(r'^mapa/', mapa,name="mapa"),
    url(r'^confirmar/', confirmarPass, name='confirmarPass'),
    # url(r'^push/', include('gcm.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#else:
#    urlpatterns += url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#            {'document_root': settings.STATIC_ROOT}),

denuncia/urls.py
from django.conf.urls import url, include
from tastypie.api import Api

from .api import MotivoResource, DenunciaResource
from .views import getDenuncias

denuncia_api = Api(api_name='d1')
denuncia_api.register(MotivoResource())
denuncia_api.register(DenunciaResource())

urlpatterns = [
    url(r'^api/', include(denuncia_api.urls)),
    url(r'^geo_denuncias/', getDenuncias, name="geo_denuncias")
]

localizaciones/urls.py
from django.conf.urls import url, include

from tastypie.api import Api

from .views import (
        busquedaM,
        busquedaD,
        obtenerD,
        estadisticas,
        municipioDetail,
        detalleZona,
        respuesta_municipio
        )
from .api import (
        DepartamentoResource,
        MunicipioResource,
        DireccionResource
        )

local_api = Api(api_name='local')
local_api.register(DepartamentoResource())
local_api.register(MunicipioResource())
local_api.register(DireccionResource())

urlpatterns = [

    url(r'^busqM/',busquedaM, name='muni'),
    url(r'^busqD/', busquedaD, name = 'dirs'),
    url(r'^obtD/', obtenerD, name='dens'),
    url(r'^muni_response/', respuesta_municipio, name='respuesta_municipio'),
    url(r'^$',estadisticas, name="estadisticas"),
    url(r'^detalleZona/', detalleZona, name='detalleZona'),
    url(r'^(?P<dep>\w+)/(?P<muni>\w+)$',municipioDetail,name='mDetail'),
    url(r'^api/', include(local_api.urls)),
]

usuario/urls.py
from django.conf.urls import url

from .views import (
                    privado,
                    registro,
                    usuarioList,
                    UsuarioDetail,
                    UsuarioEdit,
                    cambiarPass,
                    cambiarCorreo
                    )
from denuncia.views import denunciasList, DenunciaDetail

urlpatterns = [
    url(r'^$', privado, name='privado'),
    url(r'^denuncias/$', denunciasList, name='lista'),
    url(r'^denuncias/(?P<pk>\d+)/detalles/', DenunciaDetail.as_view(), name='detalles'),
    url(r'^usuarios/crear/$', registro, name="registro"),
    url(r'^usuarios/$', usuarioList, name="lista_u"),
    url(r'^usuarios/(?P<slug>\w+)/detalles/$', UsuarioDetail.as_view(), name="detalles_u"),
    url(r'^usuarios/(?P<slug>\w+)/editar/$', UsuarioEdit.as_view(), name="editar_u"),
    url(r'^cambiar_contrasena/', cambiarPass, name='cambiarPass'),
    url(r'^cambiar_correo/', cambiarCorreo, name='cambiarCorreo')

]

denuncia/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import hashlib

from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.db import models
from django.utils.encoding import smart_str, smart_unicode
from django.utils import timezone
from django.utils.encoding import smart_str, smart_unicode

"""
Tabla de la BD para guardar las denuncias.

--------------------------------------------------------------------------------
|     VARIABLE     |       TIPO      |              DESCRIPCION                |
-------------------+-----------------+------------------------------------------
|   TIPO_CHOICES   |      Tupla      |  Contiene a los tipos de denuncia que se|
|                  |                 |  pueden escoger. Se utilizan en la      |
|                  |                 |  variable 'tipo'. Utiliza como indices  |
|                  |                 |  a las 4 variables anteriores a ella.   |
--------------------------------------------------------------------------------
|        id        |       PK        |  Llave primaria de Denuncia.            |
|                  |      (INT)      |                                         |
--------------------------------------------------------------------------------
|      latitud     |    FloatField   |  Localizacion exacta de la denuncia.    |
--------------------------------------------------------------------------------
|     longitud     |    FloatField   |  Localizacion exacta de la denuncia.    |
--------------------------------------------------------------------------------
|     denuncia     |    TextField    |  Descripcion de la denuncia, puede      |
|                  |                 |  quedar en blanco.                      |
--------------------------------------------------------------------------------
|    referencia    |    CharField    |  Contiene un punto de referencia a la   |
|                  |                 |  ubucación de la denuncia.              |
--------------------------------------------------------------------------------
|      fecha       |  DateTimeField  |  Fecha y hora de la denuncia.           |
--------------------------------------------------------------------------------
|      tipo        |    CharField    |  Tipo de la denuncia, solo se puede     |
|                  |                 |  llenar con algún indice de             |
|                  |                 |  'TIPO_CHOICES'.                        |
--------------------------------------------------------------------------------
|      motivo      |       FK        |  Instancia y relación con el modelo     |
|                  |                 |  'Motivo'.                              |
--------------------------------------------------------------------------------
|     direccion    |       FK        |  Instancia y Relacion con el modelo     |
|                  |                 |  'Direccion', de la app localizaciones. |
--------------------------------------------------------------------------------
|    __unicode__   |     funcion     |  Representación del obejto como una     |
|                  |                 |  cadena, en este caso, es la 'denuncia'.|
--------------------------------------------------------------------------------
|     getSprite    |     funcion     |  Devuelve un entero con el valor de     |
|                  |                 |  la funcion 'sprite' del modelo 'motivo'|
|                  |                 |  para cortar la imagen de los marcadores|
|                  |                 |  que se muestran en el mapa.            |
--------------------------------------------------------------------------------
"""
class Denuncia(models.Model):

    CRIMINAL = 'CR'
    MUNICIPAL = 'MU'
    MEDIO_AMBIENTE = 'MA'
    DERECHOS_HUMANOS = 'DH'

    TIPO_CHOICES = (
        (CRIMINAL, 'Criminal'),
        (MUNICIPAL, 'Municipal'),
        (MEDIO_AMBIENTE, 'Medio Ambiente'),
        (DERECHOS_HUMANOS, 'Derechos Humanos'),
    )

    id = models.AutoField(primary_key=True)
    latitud = models.FloatField(blank=True, null=True)
    longitud = models.FloatField(blank=True, null=True)
    denuncia = models.TextField(blank=True)
    referencia = models.CharField(blank=True, max_length=140, default="")
    fecha = models.DateTimeField(auto_now=True, auto_now_add=False, blank = False)
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES, default=CRIMINAL)

    motivo = models.ForeignKey('Motivo')
    direccion = models.ForeignKey('localizaciones.Direccion')

    verbose_name = 'Denuncias'

    def __unicode__(self):
        return self.denuncia

    def getSprite(self):
        return self.motivo.sprite()

#Cuando se borra una denuncia, al motivo se le resta uno en cantidad
@receiver(post_delete, sender=Denuncia)
def denuncia_delete(sender, instance, **kwargs):
    instance.motivo.cantidad -= 1
    instance.motivo.save()

#Cuando se inserta una denuncia, al motivo se le suma uno en cantidad
@receiver(post_save, sender=Denuncia)
def denuncia_save(sender, instance, **kwargs):
    instance.motivo.cantidad += 1
    instance.motivo.save()

"""
Tabla de la BD que contiene los motivos que se pueden asociar a las denuncias.

--------------------------------------------------------------------------------
|     VARIABLE     |       TIPO      |              DESCRIPCION                |
-------------------+-----------------+------------------------------------------
|   TIPO_CHOICES   |      Tupla      |  Contiene a los tipos del motivo que se |
|                  |                 |  pueden escoger. Se utilizan en la      |
|                  |                 |  variable 'tipo'. Utiliza como indices  |
|                  |                 |  a las 4 variables anteriores a ella.   |
--------------------------------------------------------------------------------
|        id        |       PK        |  Llave primaria de Motivo.              |
|                  |      (INT)      |                                         |
--------------------------------------------------------------------------------
|      motivo      |    CharField    |  Motivo por el cual se puede denunciar  |
--------------------------------------------------------------------------------
|     cantidad     |   IntegerField  | Cantidad de denuncias por este motivo.  |
--------------------------------------------------------------------------------
|      tipo        |    CharField    |  Tipo del motivo, solo se puede llenar  |
|                  |                 |  con algún indice de 'TIPO_CHOICES'.    |
--------------------------------------------------------------------------------
|   instituciones  | ManyToManyField |  Relacion muchos a muchos con el modelo |
|                  |                 |  Institucion de la app institucion.     |
--------------------------------------------------------------------------------
|    __unicode__   |     funcion     |  Representación del obejto como una     |
|                  |                 |  cadena, en este caso, es el 'motivo'.  |
--------------------------------------------------------------------------------
|    motivo_hash   |     funcion     |  Retorna el 'motivo' en formato hash md5|
|                  |                 |  para poder usarlo como nombre de       |
|                  |                 |  variable en JS al renderizar el        |
|                  |                 |  template de estadisticas.              |
--------------------------------------------------------------------------------
|     sumTotal     |     funcion     |  Cantidad de denuncias por este motivo. |
--------------------------------------------------------------------------------
| get_instituciones|     funcion     |  Retorna una concatenanacion de los     |
|                  |                 |  nombres de las instituciones           |
|                  |                 |  relacionadas al motivo.                |
--------------------------------------------------------------------------------
|      sprite      |     funcion     |  Retorna un entero, resultado de una    |
|                  |                 |  operación con el id, con el fin de     |
|                  |                 |  encontrar la posición del marcador     |
|                  |                 |  correspondiente al motivo en la imagen |
|                  |                 |  '/static/images/marcadores.png'        |
--------------------------------------------------------------------------------

Meta:
--------------------------------------------------------------------------------
|   verbose_name   |      String     |  Plural del nombre del modelo.          |
--------------------------------------------------------------------------------
|     ordering     |      array      |  Lista que indica por que parametros    |
|                  |                 |  se ordena la tabla del modelo. Se      |
|                  |                 |  ordena por cantidad.                   |
--------------------------------------------------------------------------------
"""
class Motivo(models.Model):
    CRIMINAL = 'CR'
    MUNICIPAL = 'MU'
    MEDIO_AMBIENTE = 'MA'
    DERECHOS_HUMANOS = 'DH'

    TIPO_CHOICES = (
        (CRIMINAL, 'Criminal'),
        (MUNICIPAL, 'Municipal'),
        (MEDIO_AMBIENTE, 'Medio Ambiente'),
        (DERECHOS_HUMANOS, 'Derechos Humanos'),
    )

    id = models.AutoField(primary_key=True)
    motivo = models.CharField(max_length=100)
    cantidad = models.IntegerField(default=0)
    tipo = models.CharField(max_length=2, choices=TIPO_CHOICES, default=CRIMINAL)

    # correos = models.ManyToManyField('institucion.Correo')
    instituciones = models.ManyToManyField('institucion.Institucion')

    def __unicode__(self):
        splt = self.motivo.split('_')

        tmp = splt[0]
        i = 1
        while i<len(splt):
            tmp = tmp + ' ' + splt[i]

denuncia/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Denuncia, Motivo

# class CustomClearableFileInput(forms.ClearableFileInput):
#     template_with_clear = '<br>  <label for="%(clear_checkbox_id)s">%(clear_checkbox_label)s</label> %(clear)s'

class DenunciaForm(forms.ModelForm):

    class Meta:
        model = Denuncia

        fields = [
            'direccion',
            'referencia',
            'denuncia',
            'motivo',
            'tipo'
        ]

        # widgets = {
        #     'archivo': CustomClearableFileInput
        # }

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>
    {% block title %}{% endblock %} | DenunciApp
  </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href='{% static "images/logo.png" %}' type="image/png" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Montserrat|Patua+One" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <link href='{% static "css/default.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "css/barra.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "css/input.css" %}' rel="stylesheet" type="text/css" />
</head>
<body>
<div id='header-static'>
  <header id="header-wrapper">
    <div class="logo">
      <img src='{% static "images/logo_sf.png" %}' alt="DenunciApp" />
      <table>
        <tr>
          <td>
            <strong>D</strong>enunciApp
          </td>
        </tr>
      </table>
    </div>
    <div id="navbar">
      <span class="inbar">
        <ul>
          <li class="navhome"><a href="/denunciar"><span>Denuncia</span></a></li>
          <li><a href="/estadisticas"><span>Estadisticas</span></a></li>
          <li><a href="/mapa"><span>Mapa</span></a></li>
          {% if not user.is_authenticated %}
          <li><a href="/"><span>Iniciar Sesión</span></a></li>
          {% else %}
          <li class="paranga"><a href={% url 'usuario:privado' %}><span>{{user}}</span></a>
            <ul id="usuario">
              <li><a href={% url 'usuario:lista' %}><span>Denuncias</span></a></li>
              {% if user.is_staff %}
              <li><a href={% url 'usuario:lista_u' %}><span>Usuarios</span></a></li>
              <li><a href={% url 'usuario:registro' %}><span>Crear Usuario</span></a></li>
              {% endif %}
              <li><a href="/logout"><span>Cerrar Sesión</span></a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
      </span>
    </div>
  </header>

  <div class="title">
    {% block head %}
    {% endblock %}
  </div>
</div>

  <div class="jocote" align="CENTER">
    {% block content %}

    {% endblock %}
  </div>


{% block js %}


{% endblock %}

<footer id="finalPag">
  <div>
    <ul id="social">
      <li class="facebook">
        <a href="https://www.facebook.com">
          <span class='normal'>compartir</span>
        </a>
      </li>
      <li class="twitter">
        <a href="https://www.twitter.com">
          <span class='normal'>Compartir</span>
        </a>
      </li>
      <li class="google">
        <a href="https://plus.google.com">
          <span class="normal">compartir</span>
        </a>
      </li>
    </ul>
  </div>
  <p>
    © 2017
  </p>
</footer>
</body>
<script type="text/javascript" src='{% static "js/paginador.js" %}'></script>
</html>

templates/denuncia.html
{% extends 'base.html' %}

{% block title %}
  Denuncias
{% endblock %}

{% block head %}
  <h1>REALIZAR DENUNCIA</h1>
{% endblock %}

{% block content %}
<div id="section">
  <div class="messages">
    {% if messages %}
    <table>
      {% for message in messages %}
      <tr>
        <th>
          <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>...</span>{{message}}
        </th>
      </tr>
      {% endfor %}
    </table>
  {% endif %}
  </div>
  <!-- <div class = "radioBtn">
    <div class="bloqueOne">
      <input type="radio" name="tipo" value="anonimo" checked onClick="deshabilita()">
      <label>Anonima</label>
    </div>
    <div class="bloqueTwo">
      <input type="radio" name="tipo" value="personal" onClick="habilita()">
      <label>Personal</label>
    </div>
  </div> -->
  <div id="bloqueForms">
    <form id="form1" method="POST" action='' enctype='multipart/form-data'>
      {% csrf_token %}
        <div class="form-group">
          <!-- <div id="ident" style="display: none;">
            <div>
              <label>Nombre</label></br>
                {{form.nombre}} </br>
            </div>
            <div>
              <label>DPI</label></br>
                {{form.dpi}} </br>
            </div>
            <div>
              <label>Telefono</label></br>
                {{form.telefono}}</br>
            </div>
          </div> -->
          <div>
          <label>Descripcion</label></br>
            {{form.denuncia}} </br>
          </div>
          <div>
            <label>Departamento</label></br>
            <select id="dep" name="dep">
              <option value="0" selected>------</option>
              {% for dato in departamentos %}
                <option value="{{dato.id}}">{{dato.nombre}}</option>
              {% endfor %}
            </select>
          </div>
          <div>
            <label>Municipio</label></br>
            <select id="muni_id" name="muni">
              <option selected>------</option>
            </select>
          </div>
          <div>
          <label>Zona</label></br>
            {{form.direccion}} </br>
          </div>
          <div>
            <label>Referencia</label></br>
              {{form.referencia}}</br><span id="help1" class="help">....</span></br>
          </div>
          <div>
          <label>Foto/Video</label></br>
            <input type="file" id="file" name="file" accept="image/*, video/*"></br>
          </div>
          <div>
            <label>Tipo</label></br>
              {{form.tipo}} </br>
          </div>
          <div>
            <label>Motivo</label></br>
              {{form.motivo}} </br>
          </div>
          <div id="btnForm">
          </br>
            <input type="submit" class="btn btn-default" value='Enviar'>
          </br>
          </div>
          <div id="coord" style="display: none;">
            <input id="lat" type="hidden" name="lat" value=0>
            <input id="lon" type="hidden" name="lon" value=0>
          </div>
        </div>
    </form>
  </div>
</div>
{% endblock %}

{% block js %}

<script type = "text/javascript">

  // $('#logo').fadeIn(2000);

  $('#dep').on('change', busquedaMuni);
  $('#muni_id').on('change', busquedaDir);
  $('#id_tipo').on('change', busquedaMot);
  $('#help1').on('click', mostrar);
  $('#document').ready(getGeolocation);
  // $('#id_motivo').on('change', function(){
  //   if(document.getElementById('id_denuncia').value == "")
  //     document.getElementById('id_denuncia').value = $('#id_motivo option:selected').text();
  // });

  // $('select').ajaxStart(function() {
  //   console.log('hola');
  //   var img = document.createElement('img');
  //   img.src = 'static/images/ajax-loader.gif';
  //   img.id = 'cargando';
  //   img.width = '32px';
  //   img.height = '32px';
  //   $(this).before(img);
  // })

  document.getElementById('muni_id').length = 0;
  document.getElementById('id_direccion').length = 0;
  document.getElementById('id_motivo').length = 0;

  // function habilita(){
  //   document.getElementById("id_nombre").disabled = false;
  //   document.getElementById("id_dpi").disabled = false;
  //   document.getElementById("ident").style.display = 'block'
  // }
  //
  // function deshabilita(){
  //   document.getElementById("id_nombre").disabled = true;
  //   document.getElementById("id_dpi").disabled = true;
  //   document.getElementById("ident").style.display = 'none';
  // }

  function busquedaMuni(){
    // var img = document.createElement('img');
    // img.src = 'static/images/ajax-loader.gif';
    // img.id = 'cargando';
    // img.width = '32px';
    // img.height = '32px';
    // $(this).before('<img style="width=32px;" height="32px" src="static/images/ajax-loader.gif"></img>');

    var id = $(this).val();
    $.ajax({

      data: {'id': id},
      url: "{% url 'local:muni' %}",
      type: 'get',
      success: function(data){

        var inner = document.getElementById('muni_id');

        inner.innerHTML = "";
        var p = document.createElement("option");

        p.value = "0";
        p.innerHTML = "------";

        inner.options.add(p);
        for (var i = 0; i<data.length; i++){

          var nuevo = document.createElement("option");

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.nombre;

          inner.options.add(nuevo);

        }
        // img.parentNode.removeChild(img);
      },
      error: function(){
        alert('Ocurrió un error con el servidor, intenta de nuevo más tarde.');
        img.parentNode.removeChild(img);
      }

    })

  }

  function busquedaDir(){

    var id = $(this).val();
    $.ajax({

      data: {'id': id},
      url: "{% url 'local:dirs' %}",
      type: 'get',
      success: function(data){
        document.getElementById('id_direccion').length = 0;

        var inner = document.getElementById('id_direccion');
        console.log(inner);

        for(var i = 0; i<data.length; i++){

          var nuevo = document.createElement("option");

          console.log(data[i].fields.direccion);

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.direccion;

          inner.options.add(nuevo);

        }

      },
      error: function(){
        alert('Ocurrió un error con el servidor, intenta de nuevo más tarde.')
      }

    })

  }

  function busquedaMot(){

    var id = $('#id_tipo').val();
    $.ajax({

      data: {'id': id},
      url: '/busqMot/mots',
      type: 'get',
      success: function(data){

        document.getElementById('id_motivo').length = 0;

        var inner = document.getElementById('id_motivo');
        console.log(inner);

        for(var i = 0; i<data.length; i++){

          var nuevo = document.createElement("option");

          nuevo.value = data[i].pk;
          nuevo.innerHTML = data[i].fields.motivo;

          inner.options.add(nuevo);

        }

      },
      error: function(){
        alert('Ocurrió un error con el servidor, intenta de nuevo más tarde.')
      }

    })

  }

  function mostrar(){
    alert('Escribe un punto de referencia a la direccion.')
  }

	function getGeolocation() {
    busquedaMot();
		if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(function(position){

          var lat = position.coords.latitude;
          var lon = position.coords.longitude;

          document.getElementById('lat').value = lat;
          document.getElementById('lon').value = lon;
        });
		} else {
			alert("Para utilizar la geolocalización necesitas actualizar tu navegador.");
		}
	}

</script>

{% endblock %}

templates/inicio.html
{% extends 'base.html' %}

{% block head %}
<div class="title">
  <h2>{{titulo}}</h2>
</div>
{% endblock %}

{% block content %}
  <ul>
    <li><a href="/denunciar" accesskey="1" title="">Denunciar</a></li>
  </ul>
{% endblock %}

templates/municipio_detail.html
{% extends 'base.html' %}

{% block title %}
{{municipio.nombre}}
{% endblock %}

{% block head %}
  <h1>{{municipio.nombre}}, {{municipio.departamento}}</h1>
{% endblock %}

{% block content %}
<div id="section">
  <div id="chart"></div>
  <div id="dashboard_div">
    <div id="filter_div"></div>
    <div id = "piechart"></div>
  </div>
</div>
{% endblock %}

{% block js %}
<script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

google.charts.load('visualization', '1', {'packages': ['corechart']});
google.charts.setOnLoadCallback(draw);
$('#piechart').hide();

function draw() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ["Zona", "Denuncias", {role: 'annotation'}, "id"],
          {% for dato in dirs %}
            ['{{dato.direccion}}',{{dato.sumDenuncias}}, '{{dato.sumDenuncias}}',{{dato.id}}],
          {% endfor %}
        ]);

    var options = {
      title : 'Denuncias del Municipio',
      hAxis: {title: 'Denuncias'},
      vAxis: {title: 'Zona'},
      bar: {groupWidth: "75%"},
      legend: { position: "none" },
      animation:{
          duration: 1500,
          easing: 'out',
          startup: true,
      },
      colors: ['#4370bb'],
      hAxis:{
        format: 'decimal',
        minValue: 0,
      },
    };

    var chart = new google.visualization.BarChart(document.getElementById('chart'));

    google.visualization.events.addListener(chart, 'ready', function () {
      var print = document.createElement('a');
      var span = document.createElement('span');
      var text = document.createTextNode('Imprimir');
      print.id = 'print';
      print.title = 'Version para imprimir.'
      print.href = chart.getImageURI();
      print.target = '_blank';
      span.id = 'normal';
      span.appendChild(text);
      print.appendChild(span);
      document.getElementById("chart").appendChild(print);
    });

    var view = new google.visualization.DataView(data);
    view.hideColumns([3]);

    chart.draw(view, options);

    google.visualization.events.addListener(chart, 'select', function(){

      try{
        var seleccion = chart.getSelection();
        var zona = data.getValue(seleccion[0].row, 3);

        $("#piechart").show();

        var pos = $('#piechart').offset();
        window.scrollTo(pos.left, pos.top-80);

        $.ajax({

          data: {'zona': zona},
          url: "{% url 'local:detalleZona' %}",
          type: 'get',
          success: function(data) {

            var datos = google.visualization.arrayToDataTable([
              ['Motivo', 'Tipo', 'Denuncias'],
              {% for motivo in motivos %}
                ['{{motivo}}', '{{motivo.tipo}}', data[0].mots.{{motivo.motivo_hash}}],
              {% endfor %}
            ]);

            var opciones = {
              title: data[0].fields.direccion,
              pieHole: 0.35,
            }

            var grafica = new google.visualization.PieChart(document.getElementById('piechart'));

            google.visualization.events.addListener(grafica, 'ready', function () {
              var print = document.createElement('a');
              var span = document.createElement('span');
              var text = document.createTextNode('Imprimir');
              print.id = 'print';
              print.title = 'Version para imprimir.'
              print.href = grafica.getImageURI();
              print.target = '_blank';
              span.id = 'normal';
              span.appendChild(text);
              print.appendChild(span);
              document.getElementById('piechart').appendChild(print);
            });

            var view1 = new google.visualization.DataView(datos);
            view1.hideColumns([1]);

            grafica.draw(view1, opciones);

          },
          error: function(){
            alert('Ocurrió un error con el servidor, intenta de nuevo más tarde.')
          }

        });
      }catch(err){

      }
    });
  }

</script>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% block title %}
Enviado
{% endblock %}

{% block head %}
<h1>DENUNCIA ENVIADA</h1>
{% endblock %}

{% block content %}
<div id="section">
  <div class="alineacionAlCentro">
    <div id="segundoBloque">
		  <div class = "title">
        <h1> Su denuncia ha sido enviada con exito. </h1>
        </br>
        <h3><i><a href='/denunciar'>Regresar.</a></i></h3>
		  </div>
	  </div>
  </div>
</div>
{% endblock %}